<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_desOver</name>
   <tag></tag>
   <elementGuidId>981da50d-a2bd-428a-ac61-346e7cc4c9ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'gadgets-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;simple-page-scroll ng-scope&quot;]</value>
      <webElementGuid>75ac072a-851a-4b73-8b7f-adab3ee2d226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca6ea5e0-228a-450b-b06f-fceacab33b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gadgets-menu</value>
      <webElementGuid>9fda0fff-3468-44f6-963d-54a053d7379e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
